FROM oven/bun:1 AS bun

FROM node:20

COPY --from=bun /usr/local/bin/bun /usr/local/bin/bun

COPY zscaler-root-public-cert /etc/ssl/certs/zscaler-root.pem
RUN c_rehash
ENV NODE_EXTRA_CA_CERTS=/etc/ssl/certs/zscaler-root.pem

RUN mkdir /app
WORKDIR /app

ADD ./weathergov/frontend/package.json .
ADD ./weathergov/frontend/bun.lock .

RUN bun install --frozen-lockfile
